# Generated by Django 6.0.5 on 2026-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('current_stock', models.IntegerField()),
                ('units_ordered', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=50)),
                ('lead_time', models.IntegerField(default=7)),
                ('supplier_reliability', models.FloatField(default=0.95)),
                ('warehouse_location', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
