# Generated by Django 6.0.5 on 2026-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('promotion_active', models.BooleanField(default=False)),
                ('marketing_spend', models.FloatField(default=0.0)),
                ('previous_month_sales', models.FloatField(default=0.0)),
                ('forecasted_demand', models.IntegerField()),
                ('demand_trend', models.CharField(default='Stable', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('revenue_forecast', models.FloatField(default=0.0)),
                ('stockout_risk', models.CharField(default='Low', max_length=20)),
                ('overstock_risk', models.CharField(default='Low', max_length=20)),
                ('suggested_reorder_quantity', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='LightGBM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
