# Generated by Django 6.0.5 on 2026-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasthistory',
            name='economic_condition',
            field=models.CharField(default='Average', max_length=50),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='epidemic_pandemic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='festival_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='fuel_price_index',
            field=models.FloatField(default=3.5),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='inflation_rate',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='season',
            field=models.CharField(default='Summer', max_length=50),
        ),
        migrations.AddField(
            model_name='forecasthistory',
            name='weather_condition',
            field=models.CharField(default='Sunny', max_length=50),
        ),
    ]
